services:
  service-pac-demo:
    image: build-base-image:latest
    container_name: container-pac-demo
    volumes:
      - .:/project
    ports:
      - "8080:8080"
    entrypoint: /project/entrypoint.sh