services:
  service-java-time:
    # use below commented line if you built the base Java image on your local. Building this image takes 10 minutes.
    image: build-java-image:latest
    container_name: container-java-time
    volumes:
      - ../../../../:/project
    entrypoint: /project/perf/scripts/java/time/entrypoint.sh